apiVersion: v1
kind: Service              # 1
metadata:
  name: jenkins 
spec:
  type: LoadBalancer       # 2
  ports: 
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30001 
    protocol: TCP
  selector:                # 6
    app: jenkins       # 7
