apiVersion: extensions/v1beta1
kind: Deployment                                          # 1
metadata:
  name: jenkins 
spec:
  replicas: 1                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:                                               # 6
    metadata:
      labels:
        app: jenkins                                  # 7
    spec:
      containers:
        - image: vikramnagarkar/jenkins_master_image:v1.0.1
          imagePullPolicy: Always                         # 8
          name: jenkins 
          ports:
            - containerPort: 8080 
            - containerPort: 50000
